### ISSUE TITLE
Dicas Projeto

### ISSUE THREAD

**Issue by mattvianna** [manzolirch/create-with-pure-code#1]
Acho que talvez poderíamos iniciar um projeto único, por exemplo, pegamos a galeria de foto e todos vão trabalhando nele com diferentes branchs e depois unimos isso.
A ideia é o trabalho em conjunto mesmo.

**Comment by manzoliric** [comment]
Acho que deveria ter as duas coisas.. tanto projeto solo quem quiser pegar alguma das ideias e praticar sozinho, beleza, mas também poderíamos criar repositórios fixos e a galera ir se ajudando e codando.

Acho que o ideal seria criar um repositório pra cada ideia e o pessoal ir enviando pull-request, ideias pelas issues e ver aonde dá :)

**Comment by mattvianna** [comment]
Pode ser também, eu pilharia de trabalhar junto na galeria de fotos.

**Comment by manzoliric** [comment]
Bora fazer o seguinte então, começa o projeto, cria um repositório dele e posta aqui, que irei abrir uma seção em projetos para colocar "Projetos em andamento, contribua" fechou? :D

**Comment by rafaelangical** [comment]
Opaa, to dentro: )

**Comment by manzoliric** [comment]
Fala pessoal, criei um novo projeto para a galeria, podem fazer um Fork e mandar bala na galeria e depois mandar um Pull Request para eu aceitar.
https://github.com/manzolirch/gallery-pure-css

Criei uma área de colaboração também, para ficar todos os projetos em andamento que o pessoal pdoe contribuir.
https://github.com/manzolirch/create-with-pure-code/blob/master/COLLABORATE.md
